# Generated by Django 5.1.2 on 2026-09-23 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название дерева', max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Если отмечено, дерево доступно всем пользователям', verbose_name='Публичное дерево')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sync_version', models.IntegerField(default=0, help_text='Увеличивается при каждом изменении', verbose_name='Версия синхронизации')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Дерево',
                'verbose_name_plural': 'Деревья',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('maiden_name', models.CharField(blank=True, help_text='Для замужних женщин', max_length=100, null=True, verbose_name='Девичья фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_birth_date_approx', models.BooleanField(default=False, verbose_name='Приблизительная дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('is_death_date_approx', models.BooleanField(default=False, verbose_name='Приблизительная дата смерти')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('death_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место смерти')),
                ('burial_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место захоронения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Пол')),
                ('culture', models.CharField(blank=True, max_length=50, null=True, verbose_name='Культура/Национальность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('sandbox', 'Черновик'), ('published', 'Опубликовано'), ('merged', 'Объединена')], default='sandbox', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sync_version', models.IntegerField(default=0, verbose_name='Версия синхронизации')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_persons', to='genealogy.person', verbose_name='Объединена с')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_persons', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='genealogy.tree', verbose_name='Дерево')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(help_text='create/update/delete', max_length=50, verbose_name='Тип изменения')),
                ('proposed_data', models.JSONField(blank=True, null=True, verbose_name='Предложенные данные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('auto_approved', 'Автоматически одобрен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('response_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к ответу')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Владелец дерева')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кем запрошено')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='genealogy.person', verbose_name='Персона')),
            ],
            options={
                'verbose_name': 'Запрос на изменение',
                'verbose_name_plural': 'Запросы на изменения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('viewer', 'Читатель')], default='viewer', max_length=20, verbose_name='Роль')),
                ('can_invite', models.BooleanField(default=False, verbose_name='Может приглашать других')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='genealogy.tree', verbose_name='Дерево')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Соавтор дерева',
                'verbose_name_plural': 'Соавторы деревьев',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Бесплатный'), ('one_time', 'Единоразовая оплата'), ('subscription', 'Подписка')], default='free', max_length=20, verbose_name='Тариф')),
                ('tier_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия тарифа')),
                ('devices_count', models.IntegerField(default=1, verbose_name='Количество устройств')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Рождение'), ('death', 'Смерть'), ('marriage', 'Брак'), ('divorce', 'Развод'), ('birth_of_child', 'Рождение ребенка'), ('education', 'Образование'), ('work', 'Работа'), ('military', 'Военная служба'), ('migration', 'Миграция'), ('religious_event', 'Религиозное событие'), ('other', 'Другое')], max_length=20, verbose_name='Тип события')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_date_approx', models.BooleanField(default=False, verbose_name='Приблизительная дата')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sync_version', models.IntegerField(default=0, verbose_name='Версия синхронизации')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='genealogy.person', verbose_name='Персона')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='genealogy.person', verbose_name='Связанная персона')),
            ],
            options={
                'verbose_name': 'Событие жизни',
                'verbose_name_plural': 'События жизни',
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['person', 'event_date'], name='genealogy_l_person__dc4c71_idx'), models.Index(fields=['event_type'], name='genealogy_l_event_t_dffb80_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('biological_parent', 'Биологический родитель'), ('adoptive_parent', 'Приемный родитель'), ('step_parent', 'Отчим/мачеха'), ('spouse', 'Супруг(а)'), ('ex_spouse', 'Бывший супруг(а)'), ('fiance', 'Жених/невеста'), ('guardian', 'Опекун'), ('godparent', 'Крестный родитель')], max_length=20, verbose_name='Тип связи')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущая связь')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sync_version', models.IntegerField(default=0, verbose_name='Версия синхронизации')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='genealogy.person', verbose_name='От кого')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='genealogy.person', verbose_name='К кому')),
            ],
            options={
                'verbose_name': 'Родственная связь',
                'verbose_name_plural': 'Родственные связи',
                'indexes': [models.Index(fields=['from_person', 'to_person'], name='genealogy_r_from_pe_c198e5_idx'), models.Index(fields=['relationship_type'], name='genealogy_r_relatio_befb74_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_person', 'to_person', 'relationship_type'), name='unique_relationship')],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='genealogy_p_last_na_eef29a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tree', 'status'], name='genealogy_p_tree_id_dfc718_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'tree'), name='unique_person_in_tree'),
        ),
        migrations.AddConstraint(
            model_name='treecollaborator',
            constraint=models.UniqueConstraint(fields=('tree', 'user'), name='unique_collaborator_per_tree'),
        ),
    ]
