# Generated by Django 5.1.2 on 2026-09-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('full', 'Полная выгрузка'), ('relative', 'Для родственника'), ('public', 'Публичная версия')], max_length=20, verbose_name='Тип экспорта')),
                ('export_format', models.CharField(choices=[('json_zip', 'JSON + ZIP'), ('gedcom', 'GEDCOM')], default='json_zip', max_length=20, verbose_name='Формат экспорта')),
                ('privacy_overrides', models.JSONField(blank=True, default=dict, verbose_name='Переопределение настроек приватности')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В процессе'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/', verbose_name='Файл экспорта')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('person_count', models.IntegerField(blank=True, null=True, verbose_name='Количество экспортированных персон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('target_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_tasks', to='genealogy.person', verbose_name='Целевая персона')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='genealogy.tree', verbose_name='Дерево')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача экспорта',
                'verbose_name_plural': 'Задачи экспорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_format', models.CharField(choices=[('json_zip', 'JSON + ZIP'), ('gedcom', 'GEDCOM')], max_length=20, verbose_name='Формат импорта')),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/%d/', verbose_name='Исходный файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В процессе'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('person_count', models.IntegerField(blank=True, null=True, verbose_name='Количество импортированных персон')),
                ('relationship_count', models.IntegerField(blank=True, null=True, verbose_name='Количество импортированных связей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_tasks', to='genealogy.tree', verbose_name='Дерево')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача импорта',
                'verbose_name_plural': 'Задачи импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_birth_date', models.BooleanField(default=False, verbose_name='Скрывать дату рождения')),
                ('hide_death_date', models.BooleanField(default=False, verbose_name='Скрывать дату смерти')),
                ('hide_birth_place', models.BooleanField(default=False, verbose_name='Скрывать место рождения')),
                ('hide_death_place', models.BooleanField(default=False, verbose_name='Скрывать место смерти')),
                ('hide_notes', models.BooleanField(default=True, verbose_name='Скрывать заметки')),
                ('hide_photos', models.BooleanField(default=False, verbose_name='Скрывать фотографии')),
                ('full_data_min_degree', models.IntegerField(default=2, help_text='1 = родители/дети, 2 = бабушки/дедушки, 3 = прабабушки и т.д.', verbose_name='Минимальная степень родства для полных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки приватности',
                'verbose_name_plural': 'Настройки приватности',
            },
        ),
    ]
