# Generated by Django 5.1.2 on 2026-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_exporttask_importtask_privacysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='change_type',
            field=models.CharField(max_length=50, verbose_name='Тип изменения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девичья фамилия'),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='full_data_min_degree',
            field=models.IntegerField(default=2, verbose_name='Минимальная степень родства для полных данных'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичное дерево'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='sync_version',
            field=models.IntegerField(default=0, verbose_name='Версия синхронизации'),
        ),
    ]
