# Generated by Django 5.1.15 on 2026-09-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_alter_changerequest_change_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person_in_tree',
        ),
    ]
